import type { Metadata } from "next";
import React, { Suspense } from "react";
import { RefineContext } from "./_refine_context";
import { ThemeProvider } from "@components/ui/theme-provider";
import "@styles/global.css";

export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-background font-sans antialiased">
        <ThemeProvider>
          <Suspense>
            <RefineContext>{children}</RefineContext>
          </Suspense>
        </ThemeProvider>
      </body>
    </html>
  );
}
