export const TEST_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRlOTViYmU3LWZjMjktNDIyMy1hMjM0LTIyYjEyNDIxMTMzNyIsImZ1bGxOYW1lIjoiQWRtaW4iLCJwaG9uZSI6IjAzNDg4NDUxNjMiLCJyb2xlIjoiYWRtaW4iLCJkZWFsZXJJZCI6bnVsbCwicmlnaHRzIjp7InVzZXJzIjpbImNyZWF0ZSIsImVkaXQiLCJkZXRhaWwiLCJkZWxldGUiLCJsaXN0Il0sIndhcnJhbnR5LWNhcmRzIjpbImNyZWF0ZSIsImVkaXQiLCJkZXRhaWwiLCJkZWxldGUiLCJsaXN0Il0sInByb2R1Y3RzIjpbImNyZWF0ZSIsImVkaXQiLCJkZXRhaWwiLCJkZWxldGUiLCJsaXN0Il0sImRlYWxlcnMiOlsiY3JlYXRlIiwiZWRpdCIsImRldGFpbCIsImRlbGV0ZSIsImxpc3QiXSwic2VydmljZXMiOlsiY3JlYXRlIiwiZWRpdCIsImRldGFpbCIsImRlbGV0ZSIsImxpc3QiXSwibWFpbnRlbmFuY2VzIjpbImNyZWF0ZSIsImVkaXQiLCJkZXRhaWwiLCJkZWxldGUiLCJsaXN0Il0sIm1haW50ZW5hbmNlLXRlbXBsYXRlcyI6WyJjcmVhdGUiLCJlZGl0IiwiZGV0YWlsIiwiZGVsZXRlIiwibGlzdCJdLCJ3YXJyYW50eS1wb2xpY2llcyI6WyJjcmVhdGUiLCJlZGl0IiwiZGV0YWlsIiwiZGVsZXRlIiwibGlzdCJdLCJkYXNoYm9hcmQiOlsiY3JlYXRlIiwiZWRpdCIsImRldGFpbCIsImRlbGV0ZSIsImxpc3QiXSwicmVwb3J0IjpbImNyZWF0ZSIsImVkaXQiLCJkZXRhaWwiLCJkZWxldGUiLCJsaXN0Il0sImNvbmZpZ3VyYXRpb24iOlsiY3JlYXRlIiwiZWRpdCIsImRldGFpbCIsImRlbGV0ZSIsImxpc3QiXSwicmVwYWlycyI6WyJjcmVhdGUiLCJlZGl0IiwiZGV0YWlsIiwiZGVsZXRlIiwibGlzdCJdLCJndWFyYW50ZWVzIjpbImNyZWF0ZSIsImVkaXQiLCJkZXRhaWwiLCJkZWxldGUiLCJsaXN0Il19LCJpYXQiOjE3NDc4MjUyMTZ9.e2UxUoYT5rAqQ9QqrwMOrdue_sy3cA8HwXc9hiTviUs';

// API Configuration
export const API_CONFIG = {
  USER_API_URL: 'https://dev.aioapi.buildappfast.io.vn/api/v1/users',
  BEARER_TOKEN: TEST_KEY,
};

// Functions for API handling
export const getApiHeaders = () => {
  return {
    'Authorization': `Bearer ${API_CONFIG.BEARER_TOKEN}`,
    'Content-Type': 'application/json',
  };
};